### ISSUE TITLE
Will this ever be available in every terminal?

### ISSUE THREAD

**Issue by Hello-Helo** [refactorsaurusrex/journal-cli#64]
I really like the idea of this tool and I think it would reach a lot more people if you could use in any terminal emulator, not just in powershell, like an application in the arch AUR. Is this possible? And if is, can we expect in the near future?

**Comment by refactorsaurusrex** [comment]
Can you elaborate on what exactly you mean by "use in any terminal emulator"? I ask because you can already use it in any _terminal emulator_: just run `pwsh` to switch to PowerShell and proceed to use the tool. (Caveat: I am not familiar with arch AUR.) However, I suspect what you're asking for is a generic, non-PowerShell interface that can be invoked from any _shell_ much like `git`. The answer to that question is no, I have no plans to do that. I started going down that path about eight months ago, and it proved to be a huge amount of work in exchange for questionable returns on the investment. I'm sure such an interface would mollify the anti-PowerShell crowd, but so many aspects of `journal-cli` rely on native PowerShell functionality that developing generic alternatives felt wasteful. In the end, I abandoned the effort. While it is disappointing that some folks can't or won't try `journal-cli` because of PowerShell, my position is that PowerShell has come a long way in the last five or so years and has become pretty darn cool. I encourage everyone to try it, despite any misgivings. :-) 

Please let me know if I misunderstood your question.
