### ISSUE TITLE
Select tag from pre-determined set of tags

### ISSUE THREAD

**Issue by lboening** [refactorsaurusrex/journal-cli#66]
## Is your feature request related to a problem? Please describe.
When I create a new entry, I add a tag. Usually time has passed--a day or two--since I last added an entry. I usually cannot remember the tags I may have used. I fumble around trying to remember what tags I may have used. I open my journal entry folder and just take a look.

## Describe the solution you'd like
Select tags from a list of dynamically selected tags or from a hash of available tags

## Describe alternatives you've considered
Run "Get-JournalIndex | select-object -property Tag", then eyeball a tag, mentally select, then use existing tag as entry.

Or, create a function that would allow you to create a predetermined list of tags. I could be "New-JournalTag -tag mynewtag", or something similar.

## Additional context
Tag management can be an outstanding feature when added to documents! I also dream of being able to change tags that may exist in entries. Controlled-values are the way to go!

**Comment by refactorsaurusrex** [comment]
Hey @lboening, thanks for the idea!

I too have struggled with this problem. So far, I've just accepted it as an unfortunate consequence of `journal-cli` existing separately from the text editor. I'm definitely open to suggestions here. Can you elaborate on what you mean by "select tags from a list of dynamically selected tags or from a hash of available tags"? Dynamic in what sense? I want to understand how I can produce a meaningful yet small list of tags as suggestions. It would be fairly trivial to write a function that returns tags ordered from most to least recently used, or the x number of most recently used tags. Let me know your thoughts on that.

Note that you can also [rename tags](https://github.com/refactorsaurusrex/journal-cli/wiki/Rename-JournalTag). I originally wrote this function because I found I was creating tags like `coding`, `nerding`, and `developing` which all mean the same thing. When that happens, I just consolidate by running something like `Rename-JournalTag -OldTag 'nerding' -NewTag 'coding'`.

**Comment by refactorsaurusrex** [comment]
I was just reading about dynamic tab completion in PowerShell. I could use this so that when you type `New-JournalEntry -Tags {ctrl+space}`, you will be presented with a list of recently used tags. I may limit this to a specific number based on how it looks. I'll have to experiment a bit with it.

- note to self: https://adamtheautomator.com/powershell-parameters-argumentcompleter/

**Comment by lboening** [comment]
Thanks for quick response! The following code is what I have been experimenting with:

```powershell
function Get-ValidValues {
    <#
        .Synopsis
        Invoke Get-Validvalues 

        .Description
        Returns a set of valid values using the Get-JournalIndex function


    #>
    [CmdletBinding()]
    param()
    (Get-JournalIndex | select-object -expandproperty Tag)
}

function Get-MyTags {
    <#
        .SYNOPSIS
        Get-MyTags demo

        .DESCRIPTION
        Demonstration of Argument Completer feature

        .link
        https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.1&WT.mc_id=ps-gethelp
        
        https://vexx32.github.io/2018/11/29/Dynamic-ValidateSet/

    #>
    [CmdletBinding()]
    param(
        [Parameter(Position = 0, Mandatory)]
        [ArgumentCompleter(
            {
                param($Command, $Parameter, $WordToComplete, $CommandAst, $FakeBoundParams)
                Get-ValidValues                 
            }
        )]
        [string]
        $tag
    )

    Write-Warning -message ('You have selected ' + $tag)
}

## Demo: the value "work" exists on a journal entry
Get-MyTags -tag Work

## Demo: the value "Worker" does not exist in any. With no validation parameter, it still works
Get-MyTags -tag Worker
```

**Comment by refactorsaurusrex** [comment]
I think we're on the same page. I'll start working on it as soon as I can...

**Comment by lboening** [comment]
How is it going? Any tech issues?

**Comment by refactorsaurusrex** [comment]
Should be out on the next day or so....

**Comment by refactorsaurusrex** [comment]
Sorry, it will be a bit longer than expected. Stuck trying to find a solution to #60 first.

**Comment by refactorsaurusrex** [comment]
@lboening This is finally available in the beta channel. I'm going to publish the change to the PowerShell Gallery as soon as I finish re-writing the documentation. Most of the commands have been changed, but `New-JournalEntry` is largely the same, and you can use tab complete for tags now. This will also allow you to use wild cards, so for example `-Tags *tion` + `{tab}` will return "vacation". This is a really old ticket, so I'm not sure if you're even still using the tool any longer, but if you install the beta and run `Get-Command -Module JournalCli` it will list out all the current commands. I think (hope?) they're roughly intuitive to use without documentation.
